app:
  name: go_web_test1
  port: :3000

database:
  dsn: root:root@tcp(127.0.0.1:3306)/web_test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenCons: 114

redis:
  address: 127.0.0.1:6379
  password: ""
  db: 0
