app:
  name: go-web
  port: :3000

database:
  dsn: root:123456789@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenCons: 114

redis:
  address: 127.0.0.1:6379
  password: ""
  db: 0
